[doc]
name = "motivation_letter"
bundle = "https://data1b.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "motivation_letter_FOOBAR"
type = "pdf"
inputs = [
    "_preamble.tex",
    "index.tex",
    "_postamble.tex",
]
